### ISSUE TITLE
ClassCastException with Pagealbe only method argument

### ISSUE THREAD

**Issue by kreuzman** [hawkore/ignite-hk#1]
Hi,
while trying your ignite-spring-data_2.0 module I encounter bug with repository query method defined with only Pageable argument. While debugging I located the problem in IgniteRepositoryQuery#prepareQuery method where Pageable/Sort object is not removed from parameters and then is converted in IgniteCacheProxyImpl#convertToBinary method into BinaryObjectImpl object which causes a problem later on.

Example:
```
public class TestRepository {

    @Query(...custom query...)
    Page<...custom object...> findAll(Pageable page);

}
```
Stacktrace:
```
java.lang.ClassCastException: class org.apache.ignite.internal.binary.BinaryObjectImpl cannot be cast to class org.springframework.data.domain.Pageable (org.apache.ignite.internal.binary.BinaryObjectImpl and org.springframework.data.domain.Pageable are in unnamed module of loader 'app')

	at org.apache.ignite.springdata20.repository.query.IgniteRepositoryQuery.transformQueryCursor(IgniteRepositoryQuery.java:473)
	at org.apache.ignite.springdata20.repository.query.IgniteRepositoryQuery.execute(IgniteRepositoryQuery.java:314)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.lambda$invoke$3(RepositoryFactorySupport.java:595)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:595)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy69.findAll(Unknown Source)
```

**Comment by mnusan** [comment]
This issue was resolved in the latest version (2.8.1-hk-SNAPSHOT). It has been integrated into the official version of Ignite, predictably it will be available in official version 2.9. See https://issues.apache.org/jira/browse/IGNITE-13005
